import type { CatalogItem, BoxSpec, BoxRule, PackUnit, RuleSource } from './types.ts'

const rangeRule = (
  itemId: string,
  unit: PackUnit,
  min: number,
  max: number,
  source: RuleSource,
  note?: string,
): BoxRule => ({
  itemId,
  unit,
  quantity: { min, max },
  source,
  note,
})

const noteRule = (
  itemId: string,
  unit: PackUnit,
  source: RuleSource,
  note: string,
): BoxRule => ({
  itemId,
  unit,
  quantity: { min: null, max: null },
  source,
  note,
})

export const itemCatalog: CatalogItem[] = [
  { id: '151', label: '151', aliases: ['151'], preferredUnit: 'B' },
  { id: 'BBDX', label: 'BBDX', aliases: ['bbdx'], preferredUnit: 'B', multiplier: 0.77 },
  { id: 'WFDX', label: 'WFDX', aliases: ['wfdx'], preferredUnit: 'B', multiplier: 0.77 },
  { id: 'OP', label: 'OP', aliases: ['one piece op'], preferredUnit: 'B' },
  { id: 'PRB', label: 'PRB', aliases: ['prb'], preferredUnit: 'B' },
  { id: 'PRB-01', label: 'PRB-01', aliases: ['prb01'], preferredUnit: 'C' },
  { id: 'PRB-02', label: 'PRB-02', aliases: ['prb02'], preferredUnit: 'C' },
  { id: 'OP-08', label: 'OP-08', aliases: ['op08'], preferredUnit: 'C' },
  { id: 'OP-09', label: 'OP-09', aliases: ['op09'], preferredUnit: 'B' },
  { id: 'VSTAR', label: 'VSTAR', aliases: ['vstar'], preferredUnit: 'C' },
  { id: 'テラスタル', label: 'テラスタル', aliases: ['terasutaru', 'テラス'], preferredUnit: 'B' },
  { id: 'トウホク', label: 'トウホク', aliases: ['touhoku'], preferredUnit: 'B' },
  { id: 'ラブブビッグ', label: 'ラブブビッグ', aliases: ['labubu big'], preferredUnit: '個' },
  { id: 'ラブブマカロン', label: 'ラブブマカロン', aliases: ['labubu macaron'], preferredUnit: '個' },
  { id: 'ラブブコーラ', label: 'ラブブコーラ', aliases: ['labubu cola'], preferredUnit: '個' },
  { id: 'マリィ', label: 'マリィ', aliases: ['marnie'], preferredUnit: 'BOX' },
  { id: 'OPストレージBOX', label: 'OPストレージBOX', aliases: ['op storage box', 'opストレージbox', 'opストーレージbox'], preferredUnit: '個' },
  { id: 'OPストレージBOXセット', label: 'OPストレージBOXセット', aliases: ['op storage box set'], preferredUnit: 'BOX' },
  { id: 'メガトレーナー', label: 'メガトレーナー', aliases: ['mega trainer'], preferredUnit: 'B' },
  { id: 'ワンピースストレージBOX', label: 'ワンピースストレージBOX', aliases: ['one piece storage box'], preferredUnit: 'BOX' },
  { id: 'smisuki', label: 'smisuki', aliases: ['smiski'], preferredUnit: '個' },
  { id: 'キューピー(Dog)', label: 'キューピー(Dog)', aliases: ['qpie dog'], preferredUnit: '個' },
  { id: 'ユニアリ', label: 'ユニアリ', aliases: ['uni ari'], preferredUnit: 'C' },
  { id: 'ロルカナ', label: 'ロルカナ', aliases: ['lorcana'], preferredUnit: 'C' },
  { id: 'リーリエ', label: 'リーリエ', aliases: ['lillie'], preferredUnit: '個' },
  { id: 'アタッシュケース', label: 'アタッシュケース', aliases: ['attache case'], preferredUnit: '個' },
  { id: 'ソニーエンジェル', label: 'ソニーエンジェル', aliases: ['sony angel'], preferredUnit: '個' },
]

export const boxCatalog: BoxSpec[] = [
  {
    id: 'box-1',
    order: 1,
    boxNo: '1',
    partNo: 'MA60-033',
    sizeGroup: '60',
    outerSize: '23 × 18 × 18 cm',
    volumetricWeight: 1.49,
    unitPriceYen: 64,
    rules: [
      rangeRule('151', 'B', 1, 5, '備考3（BOX等）'),
      rangeRule('テラスタル', 'B', 1, 8, '備考3（BOX等）'),
      rangeRule('BBDX', 'B', 8, 8, '備考3（BOX等）'),
      rangeRule('WFDX', 'B', 8, 8, '備考3（BOX等）'),
      rangeRule('OP', 'B', 1, 4, '備考3（BOX等）'),
      rangeRule('PRB', 'B', 1, 8, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-2',
    order: 2,
    boxNo: '2',
    partNo: 'MA80-1538',
    sizeGroup: '80',
    outerSize: '29 × 21 × 24 cm',
    volumetricWeight: 2.92,
    unitPriceYen: 93,
    rules: [
      rangeRule('PRB', 'C', 1, 1, '備考1（カートン）', 'PRB01'),
      rangeRule('PRB-01', 'C', 1, 1, '備考1（カートン）'),
      rangeRule('151', 'B', 6, 8, '備考3（BOX等）', '8は平置き'),
      rangeRule('テラスタル', 'B', 9, 12, '備考3（BOX等）'),
      rangeRule('BBDX', 'B', 8, 10, '備考3（BOX等）'),
      rangeRule('WFDX', 'B', 8, 10, '備考3（BOX等）'),
      rangeRule('OP', 'B', 5, 6, '備考3（BOX等）'),
      rangeRule('PRB', 'B', 9, 10, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-3',
    order: 3,
    boxNo: '3',
    partNo: 'MA80-059',
    sizeGroup: '80',
    outerSize: '31 × 31 × 17 cm',
    volumetricWeight: 3.26,
    unitPriceYen: 113,
    note: 'PDF marks this row as 薄 / 厚.',
    rules: [
      rangeRule('151', 'C', 1, 1, '備考1（カートン）'),
      rangeRule('151', 'B', 9, 14, '備考3（BOX等）'),
      rangeRule('テラスタル', 'B', 13, 18, '備考3（BOX等）'),
      rangeRule('BBDX', 'B', 11, 18, '備考3（BOX等）'),
      rangeRule('WFDX', 'B', 11, 18, '備考3（BOX等）'),
      rangeRule('OP', 'B', 7, 9, '備考3（BOX等）'),
      rangeRule('PRB', 'B', 11, 15, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-4',
    order: 4,
    boxNo: '4',
    partNo: 'MA100-531',
    sizeGroup: '100',
    outerSize: '36 × 27 × 22 cm',
    volumetricWeight: 4.27,
    unitPriceYen: 122,
    rules: [
      rangeRule('OP', 'C', 1, 1, '備考1（カートン）'),
      rangeRule('OP-08', 'C', 1, 1, '備考1（カートン）'),
      rangeRule('テラスタル', 'B', 19, 21, '備考3（BOX等）'),
      rangeRule('PRB', 'B', 16, 18, '備考3（BOX等）'),
      rangeRule('OP', 'B', 10, 12, '備考3（BOX等）'),
      rangeRule('BBDX', 'B', 18, 18, '備考3（BOX等）'),
      rangeRule('WFDX', 'B', 18, 18, '備考3（BOX等）'),
      rangeRule('トウホク', 'B', 6, 6, '備考3（BOX等）'),
      rangeRule('ラブブビッグ', '個', 1, 1, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-5',
    order: 5,
    boxNo: '5',
    partNo: 'MA100-078',
    sizeGroup: '100',
    outerSize: '41 × 31 × 17 cm',
    volumetricWeight: 4.32,
    unitPriceYen: 133,
    rules: [
      rangeRule('VSTAR', 'C', 1, 1, '備考1（カートン）'),
      rangeRule('テラスタル', 'C', 1, 1, '備考1（カートン）'),
      rangeRule('テラスタル', 'B', 19, 30, '備考3（BOX等）'),
      rangeRule('151', 'B', 15, 18, '備考3（BOX等）'),
      rangeRule('BBDX', 'B', 22, 22, '備考3（BOX等）'),
      rangeRule('WFDX', 'B', 22, 22, '備考3（BOX等）'),
      rangeRule('OP', 'B', 13, 15, '備考3（BOX等）'),
      rangeRule('PRB', 'B', 19, 25, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-6',
    order: 6,
    boxNo: '6',
    partNo: 'MA100-1276',
    sizeGroup: '100',
    outerSize: '38 × 29 × 21 cm',
    volumetricWeight: 4.62,
    unitPriceYen: 88,
    rules: [
      rangeRule('PRB', 'C', 1, 1, '備考1（カートン）', 'PRB02'),
      rangeRule('PRB-02', 'C', 1, 1, '備考1（カートン）'),
    ],
  },
  {
    id: 'box-7',
    order: 7,
    boxNo: '7',
    partNo: 'MA100-371',
    sizeGroup: '100',
    outerSize: '43 × 32 × 25 cm',
    volumetricWeight: 6.88,
    unitPriceYen: 162,
    rules: [
      rangeRule('VSTAR', 'C', 2, 2, '備考1（カートン）'),
      rangeRule('テラスタル', 'C', 2, 2, '備考1（カートン）'),
      rangeRule('マリィ', 'BOX', 1, 13, '備考1（カートン）'),
      rangeRule('OPストレージBOX', '個', 2, 2, '備考3（BOX等）', '７番を２つ合わせる'),
      rangeRule('メガトレーナー', 'B', 10, 10, '備考3（BOX等）'),
      rangeRule('トウホク', 'B', 10, 10, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-8-thin',
    order: 8,
    boxNo: '8',
    partNo: 'MA100-030',
    sizeGroup: '100',
    outerSize: '32 × 32 × 32 cm',
    volumetricWeight: 6.55,
    unitPriceYen: 104,
    variant: '薄 / 海外',
    rules: [
      rangeRule('PRB', 'C', 2, 2, '備考1（カートン）', 'PRB01 / 薄 / 海外 / おとす'),
      rangeRule('PRB-01', 'C', 2, 2, '備考1（カートン）', '海外 / おとす'),
      rangeRule('151', 'C', 2, 2, '備考1（カートン）', '海外'),
    ],
  },
  {
    id: 'box-8-thick',
    order: 9,
    boxNo: '8',
    partNo: 'MA100-1328',
    sizeGroup: '100',
    outerSize: '32 × 32 × 34 cm',
    volumetricWeight: 6.96,
    unitPriceYen: 179,
    variant: '厚 / 国内',
    rules: [
      rangeRule('151', 'C', 2, 2, '備考1（カートン）', '国内'),
      rangeRule('PRB', 'C', 2, 2, '備考1（カートン）', 'PRB01 / 厚 / 国内 / おとす'),
      rangeRule('PRB-01', 'C', 2, 2, '備考1（カートン）', '国内 / おとす'),
      rangeRule('テラスタル', 'B', 31, 42, '備考3（BOX等）'),
      rangeRule('151', 'B', 23, 28, '備考3（BOX等）'),
      rangeRule('BBDX', 'B', 34, 34, '備考3（BOX等）'),
      rangeRule('WFDX', 'B', 34, 34, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-10',
    order: 10,
    boxNo: '10',
    partNo: 'MA120-991',
    sizeGroup: '120',
    outerSize: '36 × 36 × 37 cm',
    volumetricWeight: 9.59,
    unitPriceYen: 196,
    rules: [
      rangeRule('PRB', 'C', 4, 4, '備考1（カートン）', 'PRB01'),
      rangeRule('PRB-01', 'C', 4, 4, '備考1（カートン）'),
      rangeRule('OP-09', 'B', 32, 32, '備考1（カートン）'),
      rangeRule('smisuki', '個', 100, 100, '備考1（カートン）'),
      rangeRule('151', 'B', 29, 32, '備考3（BOX等）'),
      rangeRule('テラスタル', 'B', 43, 56, '備考3（BOX等）'),
      rangeRule('OP', 'B', 21, 32, '備考3（BOX等）'),
      rangeRule('PRB', 'B', 33, 48, '備考3（BOX等）', '容積重量注意'),
      rangeRule('BBDX', 'B', 40, 40, '備考3（BOX等）'),
      rangeRule('WFDX', 'B', 40, 40, '備考3（BOX等）'),
      rangeRule('ワンピースストレージBOX', 'BOX', 24, 24, '備考3（BOX等）'),
      rangeRule('キューピー(Dog)', '個', 100, 100, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-11',
    order: 11,
    boxNo: '11',
    partNo: 'オーダーメイド',
    sizeGroup: '120',
    outerSize: '55 × 34 × 32 cm',
    volumetricWeight: 11.96,
    unitPriceYen: 282,
    variant: '厚',
    rules: [
      rangeRule('151', 'C', 4, 4, '備考1（カートン）'),
      rangeRule('PRB', 'C', 3, 3, '備考1（カートン）', 'PRB01,02'),
      rangeRule('PRB-01', 'C', 3, 3, '備考1（カートン）', 'PRB01,02'),
      rangeRule('PRB-02', 'C', 3, 3, '備考1（カートン）', 'PRB01,02'),
      rangeRule('151', 'B', 49, 52, '備考3（BOX等）'),
      rangeRule('テラスタル', 'B', 71, 88, '備考3（BOX等）'),
      rangeRule('OP', 'B', 41, 50, '備考3（BOX等）'),
      rangeRule('BBDX', 'B', 60, 68, '備考3（BOX等）'),
      rangeRule('WFDX', 'B', 60, 68, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-12',
    order: 12,
    boxNo: '12',
    partNo: 'MA120-974',
    sizeGroup: '120',
    outerSize: '46 × 36 × 37 cm',
    volumetricWeight: 12.25,
    unitPriceYen: 211,
    variant: '厚 / 薄',
    rules: [
      rangeRule('ワンピースストレージBOX', 'BOX', 30, 30, '備考1（カートン）'),
      rangeRule('ユニアリ', 'C', 2, 2, '備考1（カートン）'),
      rangeRule('OP', 'C', 3, 3, '備考1（カートン）'),
      rangeRule('OP-08', 'C', 3, 3, '備考1（カートン）'),
      rangeRule('ロルカナ', 'C', 2, 4, '備考1（カートン）'),
      rangeRule('PRB', 'C', 5, 5, '備考1（カートン）', 'PRB01'),
      rangeRule('PRB-01', 'C', 5, 5, '備考1（カートン）'),
      rangeRule('151', 'C', 3, 3, '備考1（カートン）'),
      rangeRule('151', 'B', 33, 48, '備考3（BOX等）'),
      rangeRule('BBDX', 'B', 64, 64, '備考3（BOX等）', '下段8*4, 上段8*4'),
      rangeRule('WFDX', 'B', 64, 64, '備考3（BOX等）', '下段8*4, 上段8*4'),
      rangeRule('テラスタル', 'C', 3, 3, '備考1（カートン）'),
      rangeRule('テラスタル', 'B', 57, 70, '備考3（BOX等）'),
      rangeRule('OP', 'B', 33, 40, '備考3（BOX等）'),
      rangeRule('PRB', 'B', 49, 64, '備考3（BOX等）'),
      rangeRule('トウホク', 'B', 15, 15, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-13-upper',
    order: 13,
    boxNo: '13',
    partNo: 'K-120K',
    sizeGroup: '120',
    outerSize: '46 × 36 × 27 cm',
    volumetricWeight: 8.94,
    unitPriceYen: 156,
    variant: '薄 / 上段',
    rules: [
      rangeRule('OP', 'C', 2, 2, '備考1（カートン）'),
      rangeRule('PRB', 'C', 2, 2, '備考1（カートン）', 'PRB02 / 上下反対にしておとす'),
      rangeRule('OP-09', 'C', 2, 2, '備考1（カートン）'),
      rangeRule('PRB-02', 'C', 2, 2, '備考1（カートン）', '上下反対にしておとす'),
      rangeRule('リーリエ', '個', 10, 10, '備考3（BOX等）', 'おとす'),
    ],
  },
  {
    id: 'box-13-lower',
    order: 14,
    boxNo: '13',
    partNo: 'K-120K',
    sizeGroup: '120',
    outerSize: '46 × 36 × 18 cm',
    volumetricWeight: 5.96,
    unitPriceYen: 156,
    variant: '薄 / 下段',
    rules: [
      rangeRule('151', 'B', 19, 22, '備考3（BOX等）'),
      rangeRule('テラスタル', 'B', 40, 40, '備考3（BOX等）'),
      rangeRule('OP', 'B', 16, 20, '備考3（BOX等）'),
      rangeRule('PRB', 'B', 26, 32, '備考3（BOX等）'),
      rangeRule('OP-09', 'B', 20, 20, '備考3（BOX等）'),
      rangeRule('BBDX', 'B', 28, 28, '備考3（BOX等）'),
      rangeRule('WFDX', 'B', 28, 28, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-14',
    order: 15,
    boxNo: '14',
    partNo: 'MA140-643',
    sizeGroup: '140',
    outerSize: '52 × 42 × 44 cm',
    volumetricWeight: 19.21,
    unitPriceYen: 370,
    rules: [
      rangeRule('OP', 'C', 4, 4, '備考1（カートン）'),
      rangeRule('OP-08', 'C', 4, 4, '備考1（カートン）', 'おとす'),
      rangeRule('テラスタル', 'C', 5, 5, '備考1（カートン）', 'おとす'),
      rangeRule('アタッシュケース', '個', 2, 2, '備考1（カートン）'),
      rangeRule('151', 'B', 53, 60, '備考3（BOX等）'),
      rangeRule('BBDX', 'B', 76, 92, '備考3（BOX等）'),
      rangeRule('WFDX', 'B', 76, 92, '備考3（BOX等）'),
      rangeRule('OP', 'B', 51, 60, '備考3（BOX等）', 'おとす'),
      rangeRule('ラブブマカロン', '個', 4, 4, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-16',
    order: 16,
    boxNo: '16',
    partNo: 'K-DA012',
    sizeGroup: '140',
    outerSize: '61 × 41 × 37 cm',
    volumetricWeight: 18.5,
    note: 'PDF marks stock as unavailable.',
    rules: [
      rangeRule('OPストレージBOXセット', 'BOX', 20, 20, '備考1（カートン）', '専用'),
    ],
  },
  {
    id: 'box-dhl8',
    order: 17,
    boxNo: 'DHL8',
    partNo: 'DHL8',
    sizeGroup: '140',
    outerSize: '54 × 45 × 42 cm',
    volumetricWeight: 20.4,
    rules: [
      rangeRule('OP', 'C', 5, 5, '備考1（カートン）'),
      rangeRule('PRB', 'C', 4, 4, '備考1（カートン）', 'PRB02'),
      rangeRule('OP-08', 'C', 5, 5, '備考1（カートン）'),
      rangeRule('PRB-02', 'C', 4, 4, '備考1（カートン）'),
      rangeRule('151', 'C', 5, 5, '備考1（カートン）'),
      rangeRule('トウホク', 'B', 30, 30, '備考3（BOX等）', 'おとす'),
      rangeRule('ラブブコーラ', '個', 4, 4, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-dhl7',
    order: 18,
    boxNo: 'DHL7',
    partNo: 'DHL7',
    sizeGroup: '130',
    outerSize: '48 × 41 × 40 cm',
    volumetricWeight: 15.7,
    rules: [
      rangeRule('151', 'C', 4, 4, '備考1（カートン）'),
      rangeRule('OP', 'C', 4, 4, '備考1（カートン）'),
      rangeRule('PRB', 'C', 6, 6, '備考1（カートン）', 'PRB01'),
      rangeRule('PRB', 'C', 3, 3, '備考1（カートン）', 'PRB02'),
      rangeRule('OP-08', 'C', 4, 4, '備考1（カートン）'),
      rangeRule('PRB-01', 'C', 6, 6, '備考1（カートン）'),
      rangeRule('PRB-02', 'C', 3, 3, '備考1（カートン）'),
      noteRule('ソニーエンジェル', '個', '備考1（カートン）', 'PDF does not list a numeric quantity.'),
      rangeRule('151', 'B', 41, 60, '備考3（BOX等）'),
      rangeRule('テラスタル', 'B', 89, 90, '備考3（BOX等）'),
      rangeRule('BBDX', 'B', 76, 92, '備考3（BOX等）'),
      rangeRule('WFDX', 'B', 76, 92, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-dhl6',
    order: 19,
    boxNo: 'DHL6',
    partNo: 'DHL6',
    sizeGroup: '120',
    outerSize: '42 × 37 × 37 cm',
    volumetricWeight: 11.5,
    rules: [
      rangeRule('PRB', 'C', 4, 4, '備考1（カートン）', '画像では型番記載なし'),
      rangeRule('PRB-01', 'C', 4, 4, '備考1（カートン）'),
      rangeRule('PRB-02', 'C', 4, 4, '備考1（カートン）', '画像では型番記載なし'),
      rangeRule('151', 'B', 33, 40, '備考3（BOX等）'),
      rangeRule('BBDX', 'B', 50, 50, '備考3（BOX等）'),
      rangeRule('WFDX', 'B', 50, 50, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-dhl5',
    order: 20,
    boxNo: 'DHL5',
    partNo: 'DHL5',
    sizeGroup: '100',
    outerSize: '34 × 32 × 34 cm',
    volumetricWeight: 7.39,
    rules: [
      rangeRule('151', 'B', 17, 32, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-dhl4',
    order: 21,
    boxNo: 'DHL4',
    partNo: 'DHL4',
    sizeGroup: '86',
    outerSize: '34 × 33 × 19 cm',
    volumetricWeight: 4.26,
    rules: [
      rangeRule('151', 'B', 1, 16, '備考3（BOX等）'),
      rangeRule('BBDX', 'B', 22, 22, '備考3（BOX等）'),
      rangeRule('WFDX', 'B', 22, 22, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-fedex-small',
    order: 22,
    boxNo: 'FedEx Small',
    partNo: 'FedEx Small',
    sizeGroup: 'FedEx',
    outerSize: '33 × 26 × 33 cm',
    volumetricWeight: 7.39,
    rules: [
      rangeRule('151', 'C', 2, 2, '備考1（カートン）'),
      rangeRule('151', 'B', 24, 24, '備考3（BOX等）'),
    ],
  },
  {
    id: 'box-fedex-big',
    order: 23,
    boxNo: 'FedEx Big',
    partNo: 'FedEx Big',
    sizeGroup: 'FedEx',
    outerSize: 'Not listed clearly in PDF',
    volumetricWeight: 4.26,
    note: 'The PDF preview does not show a readable outer size for FedEx Big.',
    rules: [
      rangeRule('151', 'C', 5, 5, '備考1（カートン）'),
      rangeRule('151', 'B', 152, 152, '備考3（BOX等）'),
    ],
  },
]
